on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9].[0-9]+.[0-9]'

env:
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
  CONTAINER_IMAGE_NAME: ofertas/landing-page-front
  USER_NAME: MarcosVinicius78
  NAME_REPO: marcosvinicius78

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure a tag git mais recente
        run: |
          RAW_TAG="${GITHUB_REF#refs/tags/}"
          VERSION="${RAW_TAG#*@}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Vers√£o: $VERSION"

      - name: Docker Login GHCR
        run: |
          echo "${GHCR_TOKEN}" | docker login ghcr.io -u "${USER_NAME}" --password-stdin

      - name: Build com Docker
        run: |
          docker build -t ghcr.io/${NAME_REPO}/${CONTAINER_IMAGE_NAME}:latest \
                       -t ghcr.io/${NAME_REPO}/${CONTAINER_IMAGE_NAME}:${VERSION} .

      - name: Push no GitHub (GHCR)
        run: |
          docker push ghcr.io/${USER_NAME}/${CONTAINER_IMAGE_NAME}:latest
          docker push ghcr.io/${USER_NAME}/${CONTAINER_IMAGE_NAME}:${VERSION}